server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

logging:
  level:
    org.springframework.web: info

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
  servlet:
    # 限制上传文件大小
    multipart:
      max-request-size: 100MB # 设置上传数据总大小
      max-file-size: 10MB # 设置单个文件最大长度
